### ISSUE TITLE
is:open label:"help wanted" 

### ISSUE THREAD

**Issue by it976054056** [769484623/WiFiProbe#1]
博主 你好 谢谢你的文章和你的代码，我在编译你的代码时说缺少 libpcap.so.1
可是我已经在编译openwrt时就勾选了libpcap这个模块，可还是缺少libpcap.so.1 请问你有没有遇到这种问题 ，如果有可以给我解答吗？万分感谢

Package Scaner is missing dependencies for the following libraries:
libpcap.so.1

**Comment by 769484623** [comment]
问题收到。请在你编译的主机中编译安装libpcap。网址如下：
http://www.tcpdump.org/#latest-releases
安装后即可编译成功。

Please install libpcap first on your computer, and then re-make the ipk.

**Comment by it976054056** [comment]
大佬，非常感谢 您的热情解答。能帮我再解决一个疑问么？
我现在编译成功了mips的libpcap，并把它放到了默认的库搜索路径和mips编译工具链的库路径下，可还是不行 。还是报同样的错误。
Package Scaner is missing dependencies for the following libraries:
libpcap.so.1
然后我在库的路径下 写了一个使用libpcap库简单的 抓包程序，直接编译，说不存在此头文件。
这个程序在使用x86架构的libpcap库时，编译是通过的，而且成功运行。
zb@zb:~/hhh/openwrt-trunk/openwrt/lib/lib$ mips-openwrt-linux-gcc 1.c -o a -lpcap
1.c:11:10: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
          ^~~~~~~~
compilation terminated.
zb@zb:~/hhh/openwrt-trunk/openwrt/lib/lib$ file libpcap.so.1.8.1 
libpcap.so.1.8.1: ELF 32-bit MSB  shared object, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, not stripped``

**Comment by 769484623** [comment]
请使用make install的方式将pcap安装到你的电脑上，这样你进行ipk的生成时应该就不会有这问题了。我当初并没有直接使用linux-gcc来进行编译。有问题可以继续追问，很久以前的项目了，我记得有点不清楚。

Please install libpcap this way : [sudo] make install . And I think this can solve your problem. I didn't use linux-gcc to cross-compile this program at first time.  This project was coded long time ago, and lack of continuous maintenance, some details are blur to me. For any other problems, questions are welcomed.

**Comment by 769484623** [comment]
Libs Missing problems is solved. A typo in Makefile.
