### ISSUE TITLE
Makefile Depends error

### ISSUE THREAD

**Issue by figoym** [769484623/WiFiProbe#2]
Package Scaner is missing dependencies for the following libraries
libpcap.so.1.3
libpthread.so.0

===> Makefile line 14 ：
**DEPENDS**:=+libpcap +libpthread
DEPENDS not Depends

**Comment by 769484623** [comment]
For lib-missing problems, I solve them by building my own Openwrt firmware.
For libpthread.so.0, I simply build librt(or libpthread) into Openwrt which is in **Base->Base system**.
And libpcap.so.1.3 missing problem can be solved in this way too (forgot where it is).And of course you can directly install libpcap.ipk.
If you understand Chinese, please step to [My Blog](https://blog.csdn.net/sunhaobo1996/article/details/72898483) for more information.

**Comment by 769484623** [comment]
Problems Solved. Thx.
